name: "Cloudflare Purge Cache GitHub Action"
description: "Purge a zone's cache via the Cloudflare API"
author: aorfanos
runs:
  using: docker
  image: Dockerfile
branding:
  color: orange
  icon: cloud
